---
title: "Suggested data workflow"
author: "Beni Cakitaki - CHEEDR"
date: "26 February 2020"
output: html_notebook
---

# Introduction
Blessed users, colleagues, friends, acquaintances, and other people, as you likely already know, one of the most painful parts of working with data at CHEEDR is extracting student data through the La Trobe University Business Intelligence interface. Bad news - this package cannot alleviate that pain. Good news - all the painful stuff after extracting data is much less horrid thanks to this package. 

\    

# 1. Getting the data

Lets walk through some of the routine steps of extracting data. Open ghastly BI. You are analysing retention by campus and over time, and you want to calculate 6 year completion rates. You want a comprehensive set of enrolment variables, over 7 or 8 years. That is big data. 

- First roadblock: there is an extraction limit for BI. The size of the limit is actually quite mysterious. Indeed, scholars have spent years calculating estimates. Trial and error dictates it is something close to 250MB. You might spent a bit of time chasing this issue up with ICT, the vendor, and then your therapist. A couple of days, a teary phone call to mum, and 6 high cholesterol comfort meals later, you abandon fixing the root of problem. Gather your safety pins and duct tape, its time to find a work around.      

- Your solution is to extract the data in batches. The BI student study package query directory provides some natural delineation for organising the batches.  
You are also a really organised, highly motivated self-starter with a genuine passion for filing, so you save your queries for later use. 


